import { EmojiCategory } from "./types";

export const EXTENSION_WIDTH = 400;
export const EXTENSION_HEIGHT = 600;

export const DEFAULT_EMOJIS = ['🚀', '🔥', '✨', '💻', '🎨', '🛡️', '❤️', '✅', '⚠️', '👀', '🧠', '🤖'];

export const EMOJI_LIBRARY: EmojiCategory[] = [
  {
    id: 'smileys',
    name: 'Smileys & Emotions',
    icon: '😀',
    emojis: [
      { char: '😀', keywords: 'grinning face happy smile' },
      { char: '😃', keywords: 'grinning face with big eyes happy smile' },
      { char: '😄', keywords: 'grinning face with smiling eyes happy smile' },
      { char: '😁', keywords: 'beaming face with smiling eyes happy smile' },
      { char: '😆', keywords: 'grinning squinting face happy laugh' },
      { char: '😅', keywords: 'grinning face with sweat nervous relief' },
      { char: '🤣', keywords: 'rolling on the floor laughing funny lol' },
      { char: '😂', keywords: 'face with tears of joy funny lol cry' },
      { char: '🙂', keywords: 'slightly smiling face happy' },
      { char: '🙃', keywords: 'upside-down face silly sarcasm' },
      { char: '😉', keywords: 'winking face flirt joke' },
      { char: '😊', keywords: 'smiling face with smiling eyes happy blush' },
      { char: '😇', keywords: 'smiling face with halo angel good' },
      { char: '🥰', keywords: 'smiling face with hearts love crush' },
      { char: '😍', keywords: 'smiling face with heart-eyes love' },
      { char: '🤩', keywords: 'star-struck excited amazing' },
      { char: '😘', keywords: 'face blowing a kiss love' },
      { char: '😗', keywords: 'kissing face love' },
      { char: '😚', keywords: 'kissing face with closed eyes love' },
      { char: '😙', keywords: 'kissing face with smiling eyes love' },
      { char: '😋', keywords: 'face savoring food yum delicious' },
      { char: '😛', keywords: 'face with tongue silly' },
      { char: '😜', keywords: 'winking face with tongue silly joke' },
      { char: '🤪', keywords: 'zany face silly crazy' },
      { char: '😝', keywords: 'squinting face with tongue silly' },
      { char: '🤑', keywords: 'money-mouth face rich cash' },
      { char: '🤗', keywords: 'hugging face love care' },
      { char: '🤭', keywords: 'face with hand over mouth oops secret' },
      { char: '🤫', keywords: 'shushing face quiet silence' },
      { char: '🤔', keywords: 'thinking face hmm wonder' },
      { char: '🤐', keywords: 'zipper-mouth face secret silence' },
      { char: '🤨', keywords: 'face with raised eyebrow suspicious' },
      { char: '😐', keywords: 'neutral face meh' },
      { char: '😑', keywords: 'expressionless face meh' },
      { char: '😶', keywords: 'face without mouth silent' },
      { char: '😏', keywords: 'smirking face flirt cool' },
      { char: '😒', keywords: 'unamused face annoyed' },
      { char: '🙄', keywords: 'face with rolling eyes annoyed sarcasm' },
      { char: '😬', keywords: 'grimacing face nervous awkward' },
      { char: '🤥', keywords: 'lying face pinocchio' },
      { char: '😌', keywords: 'relieved face calm' },
      { char: '😔', keywords: 'pensive face sad thought' },
      { char: '😪', keywords: 'sleepy face tired' },
      { char: '🤤', keywords: 'drooling face hungry sleep' },
      { char: '😴', keywords: 'sleeping face tired zzz' },
      { char: '😷', keywords: 'face with medical mask sick covid' },
      { char: '🤒', keywords: 'face with thermometer sick fever' },
      { char: '🤕', keywords: 'face with head-bandage hurt injury' },
      { char: '🤢', keywords: 'nauseated face sick vomit' },
      { char: '🤮', keywords: 'face vomiting sick puke' },
      { char: '🤧', keywords: 'sneezing face sick cold' },
      { char: '🥵', keywords: 'hot face heat sweat' },
      { char: '🥶', keywords: 'cold face freeze ice' },
      { char: '🥴', keywords: 'woozy face drunk dizzy' },
      { char: '😵', keywords: 'knocked-out face dead dizzy' },
      { char: '🤯', keywords: 'exploding head mind blown shock' },
      { char: '🤠', keywords: 'cowboy hat face western' },
      { char: '🥳', keywords: 'partying face celebrate fun' },
      { char: '😎', keywords: 'smiling face with sunglasses cool' },
      { char: '🤓', keywords: 'nerd face smart study' },
      { char: '🧐', keywords: 'face with monocle classy smart' },
      { char: '😕', keywords: 'confused face' },
      { char: '😟', keywords: 'worried face anxious' },
      { char: '🙁', keywords: 'slightly frowning face sad' },
      { char: '😮', keywords: 'face with open mouth surprise' },
      { char: '😯', keywords: 'hushed face surprise quiet' },
      { char: '😲', keywords: 'astonished face shock' },
      { char: '😳', keywords: 'flushed face embarrassed' },
      { char: '🥺', keywords: 'pleading face beg cute' },
      { char: '😦', keywords: 'frowning face with open mouth shock' },
      { char: '😧', keywords: 'anguished face shock pain' },
      { char: '😨', keywords: 'fearful face scared' },
      { char: '😰', keywords: 'anxious face with sweat nervous' },
      { char: '😥', keywords: 'sad but relieved face phew' },
      { char: '😢', keywords: 'crying face sad tear' },
      { char: '😭', keywords: 'loudly crying face sad sob' },
      { char: '😱', keywords: 'face screaming in fear scared horror' },
      { char: '😖', keywords: 'confounded face frustrated' },
      { char: '😣', keywords: 'persevering face struggle' },
      { char: '😞', keywords: 'disappointed face sad' },
      { char: '😓', keywords: 'downcast face with sweat nervous' },
      { char: '😩', keywords: 'weary face tired' },
      { char: '😫', keywords: 'tired face exhausted' },
      { char: '🥱', keywords: 'yawning face tired sleep' },
      { char: '😤', keywords: 'face with steam from nose angry' },
      { char: '😡', keywords: 'pouting face angry mad' },
      { char: '😠', keywords: 'angry face mad' },
      { char: '🤬', keywords: 'face with symbols on mouth curse angry' },
      { char: '😈', keywords: 'smiling face with horns devil evil' },
      { char: '👿', keywords: 'angry face with horns devil evil' },
      { char: '💀', keywords: 'skull death dead' },
      { char: '☠️', keywords: 'skull and crossbones danger death' },
      { char: '💩', keywords: 'pile of poo poop funny' },
      { char: '🤡', keywords: 'clown face funny scary' },
      { char: '👻', keywords: 'ghost spooky' },
      { char: '👽', keywords: 'alien space' },
      { char: '👾', keywords: 'alien monster game' },
      { char: '🤖', keywords: 'robot bot tech' },
    ]
  },
  {
    id: 'hands',
    name: 'Hands & Body',
    icon: '👋',
    emojis: [
      { char: '👋', keywords: 'waving hand hello goodbye' },
      { char: '🤚', keywords: 'raised back of hand stop' },
      { char: '🖐️', keywords: 'hand with fingers splayed five stop' },
      { char: '✋', keywords: 'raised hand stop high five' },
      { char: '🖖', keywords: 'vulcan salute star trek' },
      { char: '👌', keywords: 'ok hand okay perfect' },
      { char: '🤌', keywords: 'pinched fingers italian' },
      { char: '🤏', keywords: 'pinching hand small tiny' },
      { char: '✌️', keywords: 'victory hand peace two' },
      { char: '🤞', keywords: 'crossed fingers luck hope' },
      { char: '🤟', keywords: 'love-you gesture rock' },
      { char: '🤘', keywords: 'sign of the horns rock metal' },
      { char: '🤙', keywords: 'call me hand phone shaka' },
      { char: '👈', keywords: 'backhand index pointing left' },
      { char: '👉', keywords: 'backhand index pointing right' },
      { char: '👆', keywords: 'backhand index pointing up' },
      { char: '🖕', keywords: 'middle finger rude fuck' },
      { char: '👇', keywords: 'backhand index pointing down' },
      { char: '☝️', keywords: 'index pointing up one question' },
      { char: '👍', keywords: 'thumbs up like good' },
      { char: '👎', keywords: 'thumbs down dislike bad' },
      { char: '✊', keywords: 'raised fist power fight' },
      { char: '👊', keywords: 'oncoming fist punch brofist' },
      { char: '🤛', keywords: 'left-facing fist punch' },
      { char: '🤜', keywords: 'right-facing fist punch' },
      { char: '👏', keywords: 'clapping hands applause' },
      { char: '🙌', keywords: 'raising hands celebration' },
      { char: '👐', keywords: 'open hands hug' },
      { char: '🤲', keywords: 'palms up together pray' },
      { char: '🤝', keywords: 'handshake deal agree' },
      { char: '🙏', keywords: 'folded hands pray please thanks' },
      { char: '💅', keywords: 'nail polish sassy' },
      { char: '🤳', keywords: 'selfie camera' },
      { char: '💪', keywords: 'flexed biceps strong muscle' },
      { char: '🧠', keywords: 'brain smart think' },
      { char: '🫀', keywords: 'anatomical heart love life' },
      { char: '👀', keywords: 'eyes look see' },
      { char: '👁️', keywords: 'eye look see' },
    ]
  },
  {
    id: 'animals',
    name: 'Animals & Nature',
    icon: '🐻',
    emojis: [
      { char: '🐶', keywords: 'dog face puppy pet' },
      { char: '🐱', keywords: 'cat face kitten pet' },
      { char: '🐭', keywords: 'mouse face' },
      { char: '🐹', keywords: 'hamster face pet' },
      { char: '🐰', keywords: 'rabbit face bunny' },
      { char: '🦊', keywords: 'fox face' },
      { char: '🐻', keywords: 'bear face' },
      { char: '🐼', keywords: 'panda face' },
      { char: '🐨', keywords: 'koala' },
      { char: '🐯', keywords: 'tiger face' },
      { char: '🦁', keywords: 'lion face' },
      { char: '🐮', keywords: 'cow face' },
      { char: '🐷', keywords: 'pig face' },
      { char: '🐸', keywords: 'frog face' },
      { char: '🐵', keywords: 'monkey face' },
      { char: '🐔', keywords: 'chicken bird' },
      { char: '🐧', keywords: 'penguin bird' },
      { char: '🐦', keywords: 'bird' },
      { char: '🐤', keywords: 'baby chick' },
      { char: '🦆', keywords: 'duck bird' },
      { char: '🦅', keywords: 'eagle bird' },
      { char: '🦉', keywords: 'owl bird' },
      { char: '🦇', keywords: 'bat' },
      { char: '🐺', keywords: 'wolf' },
      { char: '🐗', keywords: 'boar' },
      { char: '🐴', keywords: 'horse face' },
      { char: '🦄', keywords: 'unicorn fantasy' },
      { char: '🐝', keywords: 'honeybee insect' },
      { char: '🐛', keywords: 'bug' },
      { char: '🦋', keywords: 'butterfly' },
      { char: '🐌', keywords: 'snail' },
      { char: '🐢', keywords: 'turtle' },
      { char: '🐍', keywords: 'snake' },
      { char: '🦕', keywords: 'sauropod dinosaur' },
      { char: '🦖', keywords: 't-rex dinosaur' },
      { char: '🐙', keywords: 'octopus' },
      { char: '🦑', keywords: 'squid' },
      { char: '🦐', keywords: 'shrimp' },
      { char: '🦞', keywords: 'lobster' },
      { char: '🦀', keywords: 'crab' },
      { char: '🐡', keywords: 'blowfish' },
      { char: '🐠', keywords: 'tropical fish' },
      { char: '🐟', keywords: 'fish' },
      { char: '🐬', keywords: 'dolphin' },
      { char: '🐳', keywords: 'spouting whale' },
      { char: '🦈', keywords: 'shark' },
      { char: '🐊', keywords: 'crocodile' },
      { char: '🐅', keywords: 'tiger' },
      { char: '🐆', keywords: 'leopard' },
      { char: '🦓', keywords: 'zebra' },
      { char: '🦍', keywords: 'gorilla' },
      { char: '🐘', keywords: 'elephant' },
      { char: '🦒', keywords: 'giraffe' },
      { char: '🦘', keywords: 'kangaroo' },
      { char: '🐕', keywords: 'dog' },
      { char: '🐈', keywords: 'cat' },
      { char: '🐓', keywords: 'rooster' },
      { char: '🦃', keywords: 'turkey' },
      { char: '🦚', keywords: 'peacock' },
      { char: '🦜', keywords: 'parrot' },
      { char: '🦢', keywords: 'swan' },
      { char: '🦩', keywords: 'flamingo' },
      { char: '🕊️', keywords: 'dove peace' },
      { char: '🐇', keywords: 'rabbit' },
      { char: '🐁', keywords: 'mouse' },
      { char: '🐀', keywords: 'rat' },
      { char: '🐿️', keywords: 'chipmunk' },
      { char: '🐾', keywords: 'paw prints' },
      { char: '🐉', keywords: 'dragon' },
      { char: '🌵', keywords: 'cactus plant' },
      { char: '🎄', keywords: 'christmas tree' },
      { char: '🌲', keywords: 'evergreen tree' },
      { char: '🌳', keywords: 'deciduous tree' },
      { char: '🌴', keywords: 'palm tree' },
      { char: '🌱', keywords: 'seedling plant grow' },
      { char: '🌿', keywords: 'herb' },
      { char: '☘️', keywords: 'shamrock luck' },
      { char: '🍀', keywords: 'four leaf clover luck' },
      { char: '🍃', keywords: 'leaf fluttering in wind' },
      { char: '🍂', keywords: 'fallen leaf autumn' },
      { char: '🍁', keywords: 'maple leaf autumn' },
      { char: '🍄', keywords: 'mushroom' },
      { char: '💐', keywords: 'bouquet flowers' },
      { char: '🌷', keywords: 'tulip flower' },
      { char: '🌹', keywords: 'rose flower love' },
      { char: '🥀', keywords: 'wilted flower' },
      { char: '🌺', keywords: 'hibiscus flower' },
      { char: '🌸', keywords: 'cherry blossom flower' },
      { char: '🌼', keywords: 'blossom flower' },
      { char: '🌻', keywords: 'sunflower' },
      { char: '🌞', keywords: 'sun with face' },
      { char: '🌝', keywords: 'full moon face' },
      { char: '🌙', keywords: 'crescent moon' },
      { char: '🌎', keywords: 'globe showing americas earth' },
      { char: '🪐', keywords: 'ringed planet saturn' },
      { char: '⭐', keywords: 'star' },
      { char: '🌟', keywords: 'glowing star' },
      { char: '✨', keywords: 'sparkles magic' },
      { char: '⚡', keywords: 'high voltage lightning' },
      { char: '🔥', keywords: 'fire hot' },
      { char: '🌈', keywords: 'rainbow' },
      { char: '☀️', keywords: 'sun' },
      { char: '☁️', keywords: 'cloud' },
      { char: '❄️', keywords: 'snowflake cold' },
      { char: '💧', keywords: 'droplet water' },
      { char: '🌊', keywords: 'water wave' },
    ]
  },
  {
    id: 'food',
    name: 'Food & Drink',
    icon: '🍔',
    emojis: [
      { char: '🍇', keywords: 'grapes fruit' },
      { char: '🍈', keywords: 'melon fruit' },
      { char: '🍉', keywords: 'watermelon fruit' },
      { char: '🍊', keywords: 'tangerine fruit orange' },
      { char: '🍋', keywords: 'lemon fruit' },
      { char: '🍌', keywords: 'banana fruit' },
      { char: '🍍', keywords: 'pineapple fruit' },
      { char: '🥭', keywords: 'mango fruit' },
      { char: '🍎', keywords: 'red apple fruit' },
      { char: '🍏', keywords: 'green apple fruit' },
      { char: '🍐', keywords: 'pear fruit' },
      { char: '🍑', keywords: 'peach fruit butt' },
      { char: '🍒', keywords: 'cherries fruit' },
      { char: '🍓', keywords: 'strawberry fruit' },
      { char: '🥝', keywords: 'kiwi fruit' },
      { char: '🍅', keywords: 'tomato fruit vegetable' },
      { char: '🥥', keywords: 'coconut' },
      { char: '🥑', keywords: 'avocado' },
      { char: '🍆', keywords: 'eggplant vegetable' },
      { char: '🥔', keywords: 'potato vegetable' },
      { char: '🥕', keywords: 'carrot vegetable' },
      { char: '🌽', keywords: 'ear of corn vegetable' },
      { char: '🌶️', keywords: 'hot pepper spicy' },
      { char: '🥦', keywords: 'broccoli vegetable' },
      { char: '🥬', keywords: 'leafy green vegetable' },
      { char: '🍄', keywords: 'mushroom' },
      { char: '🥜', keywords: 'peanuts' },
      { char: '🌰', keywords: 'chestnut' },
      { char: '🍞', keywords: 'bread' },
      { char: '🥐', keywords: 'croissant' },
      { char: '🥖', keywords: 'baguette bread' },
      { char: '🥯', keywords: 'bagel' },
      { char: '🥞', keywords: 'pancakes' },
      { char: '🧇', keywords: 'waffle' },
      { char: '🧀', keywords: 'cheese wedge' },
      { char: '🍖', keywords: 'meat on bone' },
      { char: '🍗', keywords: 'poultry leg chicken' },
      { char: '🥩', keywords: 'cut of meat steak' },
      { char: '🥓', keywords: 'bacon' },
      { char: '🍔', keywords: 'hamburger burger' },
      { char: '🍟', keywords: 'french fries' },
      { char: '🍕', keywords: 'pizza' },
      { char: '🌭', keywords: 'hot dog' },
      { char: '🥪', keywords: 'sandwich' },
      { char: '🌮', keywords: 'taco' },
      { char: '🌯', keywords: 'burrito' },
      { char: '🥚', keywords: 'egg' },
      { char: '🍳', keywords: 'cooking' },
      { char: '🥘', keywords: 'shallow pan of food' },
      { char: '🍲', keywords: 'pot of food stew' },
      { char: '🥣', keywords: 'bowl with spoon' },
      { char: '🥗', keywords: 'green salad' },
      { char: '🍿', keywords: 'popcorn' },
      { char: '🧂', keywords: 'salt' },
      { char: '🥫', keywords: 'canned food' },
      { char: '🍱', keywords: 'bento box' },
      { char: '🍘', keywords: 'rice cracker' },
      { char: '🍙', keywords: 'rice ball' },
      { char: '🍚', keywords: 'cooked rice' },
      { char: '🍛', keywords: 'curry rice' },
      { char: '🍜', keywords: 'steaming bowl noodle ramen' },
      { char: '🍝', keywords: 'spaghetti pasta' },
      { char: '🍣', keywords: 'sushi' },
      { char: '🍤', keywords: 'fried shrimp' },
      { char: '🍥', keywords: 'fish cake with swirl' },
      { char: '🍦', keywords: 'soft ice cream' },
      { char: '🍧', keywords: 'shaved ice' },
      { char: '🍨', keywords: 'ice cream' },
      { char: '🍩', keywords: 'doughnut donut' },
      { char: '🍪', keywords: 'cookie' },
      { char: '🎂', keywords: 'birthday cake' },
      { char: '🍰', keywords: 'shortcake' },
      { char: '🧁', keywords: 'cupcake' },
      { char: '🥧', keywords: 'pie' },
      { char: '🍫', keywords: 'chocolate bar' },
      { char: '🍬', keywords: 'candy' },
      { char: '🍭', keywords: 'lollipop' },
      { char: '🍮', keywords: 'custard' },
      { char: '🍯', keywords: 'honey pot' },
      { char: '🍼', keywords: 'baby bottle' },
      { char: '🥛', keywords: 'glass of milk' },
      { char: '☕', keywords: 'hot beverage coffee tea' },
      { char: '🫖', keywords: 'teapot' },
      { char: '🍵', keywords: 'teacup without handle green tea' },
      { char: '🍶', keywords: 'sake' },
      { char: '🍾', keywords: 'champagne' },
      { char: '🍷', keywords: 'wine glass' },
      { char: '🍸', keywords: 'cocktail glass' },
      { char: '🍹', keywords: 'tropical drink' },
      { char: '🍺', keywords: 'beer mug' },
      { char: '🍻', keywords: 'clinking beer mugs' },
      { char: '🥂', keywords: 'clinking glasses' },
      { char: '🥃', keywords: 'tumbler glass whiskey' },
      { char: '🥤', keywords: 'cup with straw' },
      { char: '🧃', keywords: 'beverage box juice' },
      { char: '🧉', keywords: 'mate drink' },
      { char: '🧊', keywords: 'ice cube' },
      { char: '🥢', keywords: 'chopsticks' },
      { char: '🍽️', keywords: 'fork and knife with plate' },
    ]
  },
  {
    id: 'activity',
    name: 'Activities',
    icon: '⚽',
    emojis: [
      { char: '⚽', keywords: 'soccer ball football' },
      { char: '🏀', keywords: 'basketball' },
      { char: '🏈', keywords: 'american football' },
      { char: '⚾', keywords: 'baseball' },
      { char: '🥎', keywords: 'softball' },
      { char: '🎾', keywords: 'tennis' },
      { char: '🏐', keywords: 'volleyball' },
      { char: '🏉', keywords: 'rugby football' },
      { char: '🥏', keywords: 'flying disc frisbee' },
      { char: '🎱', keywords: 'pool 8 ball billiard' },
      { char: '🪀', keywords: 'yo-yo' },
      { char: '🏓', keywords: 'ping pong table tennis' },
      { char: '🏸', keywords: 'badminton' },
      { char: '🏒', keywords: 'ice hockey' },
      { char: '🏑', keywords: 'field hockey' },
      { char: '🥍', keywords: 'lacrosse' },
      { char: '🏏', keywords: 'cricket game' },
      { char: '⛳', keywords: 'flag in hole golf' },
      { char: '🏹', keywords: 'bow and arrow archery' },
      { char: '🎣', keywords: 'fishing pole' },
      { char: '🤿', keywords: 'diving mask' },
      { char: '🥊', keywords: 'boxing glove' },
      { char: '🥋', keywords: 'martial arts uniform' },
      { char: '⛸️', keywords: 'ice skate' },
      { char: '🎿', keywords: 'skis' },
      { char: '🛷', keywords: 'sled' },
      { char: '🥌', keywords: 'curling stone' },
      { char: '🛹', keywords: 'skateboard' },
      { char: '🛼', keywords: 'roller skate' },
      { char: '🩰', keywords: 'ballet shoes' },
      { char: '🏋️', keywords: 'person lifting weights' },
      { char: '🤸', keywords: 'person cartwheeling' },
      { char: '🧘', keywords: 'person in lotus position yoga' },
      { char: '🏇', keywords: 'horse racing' },
      { char: '🏆', keywords: 'trophy winner' },
      { char: '🥇', keywords: '1st place medal gold' },
      { char: '🥈', keywords: '2nd place medal silver' },
      { char: '🥉', keywords: '3rd place medal bronze' },
      { char: '🏅', keywords: 'sports medal' },
      { char: '🎖️', keywords: 'military medal' },
      { char: '🎗️', keywords: 'reminder ribbon' },
      { char: '🎫', keywords: 'ticket' },
      { char: '🎟️', keywords: 'admission tickets' },
      { char: '🎭', keywords: 'performing arts theater' },
      { char: '🎨', keywords: 'artist palette' },
      { char: '🎪', keywords: 'circus tent' },
      { char: '🎤', keywords: 'microphone' },
      { char: '🎧', keywords: 'headphone' },
      { char: '🎼', keywords: 'musical score' },
      { char: '🎹', keywords: 'musical keyboard piano' },
      { char: '🥁', keywords: 'drum' },
      { char: '🎷', keywords: 'saxophone' },
      { char: '🎺', keywords: 'trumpet' },
      { char: '🎸', keywords: 'guitar' },
      { char: '🪕', keywords: 'banjo' },
      { char: '🎻', keywords: 'violin' },
      { char: '🎲', keywords: 'game die' },
      { char: '🧩', keywords: 'puzzle piece' },
      { char: '♟️', keywords: 'chess pawn' },
      { char: '🎮', keywords: 'video game controller' },
    ]
  },
  {
    id: 'travel',
    name: 'Travel & Places',
    icon: '🚗',
    emojis: [
      { char: '🚗', keywords: 'automobile car' },
      { char: '🚕', keywords: 'taxi' },
      { char: '🚙', keywords: 'sport utility vehicle suv' },
      { char: '🚌', keywords: 'bus' },
      { char: '🚎', keywords: 'trolleybus' },
      { char: '🏎️', keywords: 'racing car' },
      { char: '🚓', keywords: 'police car' },
      { char: '🚑', keywords: 'ambulance' },
      { char: '🚒', keywords: 'fire engine truck' },
      { char: '🚐', keywords: 'minibus' },
      { char: '🚚', keywords: 'delivery truck' },
      { char: '🚛', keywords: 'articulated lorry truck' },
      { char: '🚜', keywords: 'tractor' },
      { char: '🏍️', keywords: 'motorcycle' },
      { char: '🛵', keywords: 'motor scooter' },
      { char: '🚲', keywords: 'bicycle bike' },
      { char: '🛴', keywords: 'kick scooter' },
      { char: '🛹', keywords: 'skateboard' },
      { char: '🚏', keywords: 'bus stop' },
      { char: '🚂', keywords: 'locomotive train' },
      { char: '🚃', keywords: 'railway car' },
      { char: '🚄', keywords: 'high-speed train shinkansen' },
      { char: '🚅', keywords: 'bullet train' },
      { char: '🚆', keywords: 'train' },
      { char: '🚇', keywords: 'metro subway' },
      { char: '🚈', keywords: 'light rail' },
      { char: '🚉', keywords: 'station' },
      { char: '🚊', keywords: 'tram' },
      { char: '🚝', keywords: 'monorail' },
      { char: '✈️', keywords: 'airplane' },
      { char: '🛫', keywords: 'airplane departure' },
      { char: '🛬', keywords: 'airplane arrival' },
      { char: '🛩️', keywords: 'small airplane' },
      { char: '💺', keywords: 'seat' },
      { char: '🛰️', keywords: 'satellite' },
      { char: '🚀', keywords: 'rocket' },
      { char: '🛸', keywords: 'flying saucer ufo' },
      { char: '🚁', keywords: 'helicopter' },
      { char: '🛶', keywords: 'canoe' },
      { char: '⛵', keywords: 'sailboat' },
      { char: '🚤', keywords: 'speedboat' },
      { char: '🛥️', keywords: 'motor boat' },
      { char: '🛳️', keywords: 'passenger ship' },
      { char: '⛴️', keywords: 'ferry' },
      { char: '🚢', keywords: 'ship' },
      { char: '⚓', keywords: 'anchor' },
      { char: '⛽', keywords: 'fuel pump gas' },
      { char: '🚧', keywords: 'construction' },
      { char: '🚦', keywords: 'vertical traffic light' },
      { char: '🚥', keywords: 'horizontal traffic light' },
      { char: '🚏', keywords: 'bus stop' },
      { char: '🗺️', keywords: 'world map' },
      { char: '🗿', keywords: 'moai statue' },
      { char: '🗽', keywords: 'statue of liberty' },
      { char: '🗼', keywords: 'tokyo tower' },
      { char: '🏰', keywords: 'castle' },
      { char: '🏯', keywords: 'japanese castle' },
      { char: '🏟️', keywords: 'stadium' },
      { char: '🎡', keywords: 'ferris wheel' },
      { char: '🎢', keywords: 'roller coaster' },
      { char: '🎠', keywords: 'carousel horse' },
      { char: '⛲', keywords: 'fountain' },
      { char: '⛱️', keywords: 'umbrella on ground beach' },
      { char: '🏖️', keywords: 'beach with umbrella' },
      { char: '🏝️', keywords: 'desert island' },
      { char: '🏜️', keywords: 'desert' },
      { char: '🌋', keywords: 'volcano' },
      { char: '⛰️', keywords: 'mountain' },
      { char: '🏔️', keywords: 'snow-capped mountain' },
      { char: '🗻', keywords: 'mount fuji' },
      { char: '🏕️', keywords: 'camping' },
      { char: '⛺', keywords: 'tent' },
      { char: '🏠', keywords: 'house' },
      { char: '🏡', keywords: 'house with garden' },
      { char: '🏘️', keywords: 'houses' },
      { char: '🏚️', keywords: 'derelict house' },
      { char: '🏗️', keywords: 'building construction' },
      { char: '🏭', keywords: 'factory' },
      { char: '🏢', keywords: 'office building' },
      { char: '🏬', keywords: 'department store' },
      { char: '🏣', keywords: 'japanese post office' },
      { char: '🏤', keywords: 'post office' },
      { char: '🏥', keywords: 'hospital' },
      { char: '🏦', keywords: 'bank' },
      { char: '🏨', keywords: 'hotel' },
      { char: '🏪', keywords: 'convenience store' },
      { char: '🏫', keywords: 'school' },
      { char: '🏛️', keywords: 'classical building' },
      { char: '⛪', keywords: 'church' },
      { char: '🕌', keywords: 'mosque' },
      { char: '🛕', keywords: 'hindu temple' },
      { char: '🕍', keywords: 'synagogue' },
      { char: '⛩️', keywords: 'shinto shrine' },
      { char: '🕋', keywords: 'kaaba' },
    ]
  },
  {
    id: 'objects',
    name: 'Objects & Symbols',
    icon: '💡',
    emojis: [
      { char: '💡', keywords: 'light bulb idea' },
      { char: '💢', keywords: 'anger symbol' },
      { char: '💣', keywords: 'bomb' },
      { char: '💤', keywords: 'zzz sleep' },
      { char: '💥', keywords: 'collision boom' },
      { char: '💦', keywords: 'sweat droplets' },
      { char: '💨', keywords: 'dashing away wind' },
      { char: '💫', keywords: 'dizzy star' },
      { char: '💬', keywords: 'speech balloon chat' },
      { char: '👁️‍🗨️', keywords: 'eye in speech bubble' },
      { char: '🗨️', keywords: 'left speech bubble' },
      { char: '🗯️', keywords: 'right anger bubble' },
      { char: '💭', keywords: 'thought balloon' },
      { char: '⌚', keywords: 'watch' },
      { char: '📱', keywords: 'mobile phone' },
      { char: '💻', keywords: 'laptop computer' },
      { char: '⌨️', keywords: 'keyboard' },
      { char: '🖥️', keywords: 'desktop computer' },
      { char: '🖨️', keywords: 'printer' },
      { char: '🖱️', keywords: 'computer mouse' },
      { char: '📷', keywords: 'camera' },
      { char: '📸', keywords: 'camera with flash' },
      { char: '📹', keywords: 'video camera' },
      { char: '📺', keywords: 'television tv' },
      { char: '📻', keywords: 'radio' },
      { char: '🎙️', keywords: 'microphone' },
      { char: '🔋', keywords: 'battery' },
      { char: '🔌', keywords: 'electric plug' },
      { char: '💸', keywords: 'money with wings' },
      { char: '💵', keywords: 'dollar banknote money' },
      { char: '💰', keywords: 'money bag' },
      { char: '💳', keywords: 'credit card' },
      { char: '💎', keywords: 'gem stone diamond' },
      { char: '⚖️', keywords: 'balance scale' },
      { char: '🔧', keywords: 'wrench tool' },
      { char: '🔨', keywords: 'hammer tool' },
      { char: '⚙️', keywords: 'gear settings' },
      { char: '🔫', keywords: 'pistol gun water' },
      { char: '🛡️', keywords: 'shield protect' },
      { char: '🔮', keywords: 'crystal ball magic' },
      { char: '💊', keywords: 'pill medicine' },
      { char: '🩹', keywords: 'adhesive bandage' },
      { char: '🦠', keywords: 'microbe virus' },
      { char: '🗝️', keywords: 'old key' },
      { char: '🚪', keywords: 'door' },
      { char: '🧸', keywords: 'teddy bear' },
      { char: '🖼️', keywords: 'framed picture art' },
      { char: '🛒', keywords: 'shopping cart' },
      { char: '🎁', keywords: 'wrapped gift present' },
      { char: '🎈', keywords: 'balloon' },
      { char: '🎉', keywords: 'party popper celebrate' },
      { char: '✉️', keywords: 'envelope email' },
      { char: '📦', keywords: 'package box' },
      { char: '📊', keywords: 'bar chart stats' },
      { char: '📈', keywords: 'chart increasing' },
      { char: '📉', keywords: 'chart decreasing' },
      { char: '📅', keywords: 'calendar' },
      { char: '🗑️', keywords: 'wastebasket trash' },
      { char: '📁', keywords: 'file folder' },
      { char: '📂', keywords: 'open file folder' },
      { char: '📚', keywords: 'books' },
      { char: '📖', keywords: 'open book' },
      { char: '📎', keywords: 'paperclip' },
      { char: '✂️', keywords: 'scissors' },
      { char: '📝', keywords: 'memo' },
      { char: '✏️', keywords: 'pencil' },
      { char: '🔍', keywords: 'magnifying glass tilted left search' },
      { char: '🔎', keywords: 'magnifying glass tilted right search' },
      { char: '🔒', keywords: 'locked' },
      { char: '🔓', keywords: 'unlocked' },
      { char: '❤️', keywords: 'red heart love' },
      { char: '🧡', keywords: 'orange heart love' },
      { char: '💛', keywords: 'yellow heart love' },
      { char: '💚', keywords: 'green heart love' },
      { char: '💙', keywords: 'blue heart love' },
      { char: '💜', keywords: 'purple heart love' },
      { char: '🖤', keywords: 'black heart love' },
      { char: '🤍', keywords: 'white heart love' },
      { char: '🤎', keywords: 'brown heart love' },
      { char: '💔', keywords: 'broken heart' },
      { char: '❣️', keywords: 'heart exclamation' },
      { char: '💕', keywords: 'two hearts' },
      { char: '💞', keywords: 'revolving hearts' },
      { char: '💓', keywords: 'beating heart' },
      { char: '💗', keywords: 'growing heart' },
      { char: '💖', keywords: 'sparkling heart' },
      { char: '💘', keywords: 'heart with arrow' },
      { char: '💝', keywords: 'heart with ribbon' },
      { char: '🛑', keywords: 'stop sign' },
      { char: '✅', keywords: 'check mark button' },
      { char: '✔️', keywords: 'check mark' },
      { char: '❌', keywords: 'cross mark' },
      { char: '❎', keywords: 'cross mark button' },
      { char: '❓', keywords: 'question mark' },
      { char: '❔', keywords: 'white question mark' },
      { char: '❕', keywords: 'white exclamation mark' },
      { char: '❗', keywords: 'exclamation mark' },
      { char: '⚠️', keywords: 'warning' },
      { char: '⛔', keywords: 'no entry' },
      { char: '🚫', keywords: 'prohibited' },
    ]
  },
  {
    id: 'flags',
    name: 'Flags',
    icon: '🏳️',
    emojis: [
      { char: '🏳️', keywords: 'white flag surrender' },
      { char: '🏴', keywords: 'black flag' },
      { char: '🏁', keywords: 'checkered flag race' },
      { char: '🚩', keywords: 'triangular flag' },
      { char: '🏳️‍🌈', keywords: 'rainbow flag lgbt' },
      { char: '🏳️‍⚧️', keywords: 'transgender flag' },
      { char: '🏴‍☠️', keywords: 'pirate flag skull' },
      { char: '🇺🇳', keywords: 'united nations flag' },
      { char: '🇦🇫', keywords: 'flag: afghanistan' },
      { char: '🇦🇱', keywords: 'flag: albania' },
      { char: '🇩🇿', keywords: 'flag: algeria' },
      { char: '🇦🇷', keywords: 'flag: argentina' },
      { char: '🇦🇲', keywords: 'flag: armenia' },
      { char: '🇦🇺', keywords: 'flag: australia' },
      { char: '🇦🇹', keywords: 'flag: austria' },
      { char: '🇦🇿', keywords: 'flag: azerbaijan' },
      { char: '🇧🇭', keywords: 'flag: bahrain' },
      { char: '🇧🇩', keywords: 'flag: bangladesh' },
      { char: '🇧🇪', keywords: 'flag: belgium' },
      { char: '🇧🇷', keywords: 'flag: brazil' },
      { char: '🇧🇬', keywords: 'flag: bulgaria' },
      { char: '🇰🇭', keywords: 'flag: cambodia' },
      { char: '🇨🇦', keywords: 'flag: canada' },
      { char: '🇨🇱', keywords: 'flag: chile' },
      { char: '🇨🇳', keywords: 'flag: china' },
      { char: '🇨🇴', keywords: 'flag: colombia' },
      { char: '🇨🇷', keywords: 'flag: costa rica' },
      { char: '🇭🇷', keywords: 'flag: croatia' },
      { char: '🇨🇺', keywords: 'flag: cuba' },
      { char: '🇨🇿', keywords: 'flag: czechia' },
      { char: '🇩🇰', keywords: 'flag: denmark' },
      { char: '🇩🇴', keywords: 'flag: dominican republic' },
      { char: '🇪🇨', keywords: 'flag: ecuador' },
      { char: '🇪🇬', keywords: 'flag: egypt' },
      { char: '🇸🇻', keywords: 'flag: el salvador' },
      { char: '🇫🇮', keywords: 'flag: finland' },
      { char: '🇫🇷', keywords: 'flag: france' },
      { char: '🇩🇪', keywords: 'flag: germany' },
      { char: '🇬🇷', keywords: 'flag: greece' },
      { char: '🇬🇹', keywords: 'flag: guatemala' },
      { char: '🇭🇳', keywords: 'flag: honduras' },
      { char: '🇭🇰', keywords: 'flag: hong kong sar china' },
      { char: '🇭🇺', keywords: 'flag: hungary' },
      { char: '🇮🇸', keywords: 'flag: iceland' },
      { char: '🇮🇳', keywords: 'flag: india' },
      { char: '🇮🇩', keywords: 'flag: indonesia' },
      { char: '🇮🇷', keywords: 'flag: iran' },
      { char: '🇮🇶', keywords: 'flag: iraq' },
      { char: '🇮🇪', keywords: 'flag: ireland' },
      { char: '🇮🇱', keywords: 'flag: israel' },
      { char: '🇮🇹', keywords: 'flag: italy' },
      { char: '🇯🇲', keywords: 'flag: jamaica' },
      { char: '🇯🇵', keywords: 'flag: japan' },
      { char: '🇯🇴', keywords: 'flag: jordan' },
      { char: '🇰🇿', keywords: 'flag: kazakhstan' },
      { char: '🇰🇪', keywords: 'flag: kenya' },
      { char: '🇰🇼', keywords: 'flag: kuwait' },
      { char: '🇱🇧', keywords: 'flag: lebanon' },
      { char: '🇲🇾', keywords: 'flag: malaysia' },
      { char: '🇲🇽', keywords: 'flag: mexico' },
      { char: '🇲🇦', keywords: 'flag: morocco' },
      { char: '🇳🇵', keywords: 'flag: nepal' },
      { char: '🇳🇱', keywords: 'flag: netherlands' },
      { char: '🇳🇿', keywords: 'flag: new zealand' },
      { char: '🇳🇬', keywords: 'flag: nigeria' },
      { char: '🇰🇵', keywords: 'flag: north korea' },
      { char: '🇳🇴', keywords: 'flag: norway' },
      { char: '🇴🇲', keywords: 'flag: oman' },
      { char: '🇵🇰', keywords: 'flag: pakistan' },
      { char: '🇵🇸', keywords: 'flag: palestinian territories' },
      { char: '🇵🇦', keywords: 'flag: panama' },
      { char: '🇵🇾', keywords: 'flag: paraguay' },
      { char: '🇵🇪', keywords: 'flag: peru' },
      { char: '🇵🇭', keywords: 'flag: philippines' },
      { char: '🇵🇱', keywords: 'flag: poland' },
      { char: '🇵🇹', keywords: 'flag: portugal' },
      { char: '🇵🇷', keywords: 'flag: puerto rico' },
      { char: '🇶🇦', keywords: 'flag: qatar' },
      { char: '🇷🇴', keywords: 'flag: romania' },
      { char: '🇷🇺', keywords: 'flag: russia' },
      { char: '🇸🇦', keywords: 'flag: saudi arabia' },
      { char: '🇸🇬', keywords: 'flag: singapore' },
      { char: '🇿🇦', keywords: 'flag: south africa' },
      { char: '🇰🇷', keywords: 'flag: south korea' },
      { char: '🇪🇸', keywords: 'flag: spain' },
      { char: '🇱🇰', keywords: 'flag: sri lanka' },
      { char: '🇸🇪', keywords: 'flag: sweden' },
      { char: '🇨🇭', keywords: 'flag: switzerland' },
      { char: '🇹🇼', keywords: 'flag: taiwan' },
      { char: '🇹🇭', keywords: 'flag: thailand' },
      { char: '🇹🇷', keywords: 'flag: turkey' },
      { char: '🇺🇦', keywords: 'flag: ukraine' },
      { char: '🇦🇪', keywords: 'flag: united arab emirates' },
      { char: '🇬🇧', keywords: 'flag: united kingdom' },
      { char: '🇺🇸', keywords: 'flag: united states' },
      { char: '🇺🇾', keywords: 'flag: uruguay' },
      { char: '🇻🇪', keywords: 'flag: venezuela' },
      { char: '🇻🇳', keywords: 'flag: vietnam' },
    ]
  }
];

// Fallback for development outside of Chrome Extension environment
export const IS_DEV = !(globalThis as any).chrome?.storage;